GET localhost:8080/api/v1/auth/customers
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyIiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6ODA4MC9hcGkvbG9naW4iLCJleHAiOjE2OTM0MTQ3NzR9.iPV1lVTcG3xxcWrnqcqual1NJNpYpEFPt3CgD6bgdIo