GET localhost:8080/api/v1/auth/getUsername
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyMiIsInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODAvYXBpL2xvZ2luIiwiZXhwIjoxNjkzNDEzMjk4fQ.UKZ3PjnNLK5UVDESH_4dIfbXmUomEdgab60v-SWzjqs